### ISSUE TITLE
drop of custom items even though BlockBreakEvent is cancelled with priority highest

### ISSUE THREAD

**Issue by Padlick01** [LoneDev6/ItemsAdder#34]
As the title says, when you break for example nether quartz ore, ItemsAdder drops Items even though BlockBreakEvent with priority highest is cancelled.

**Comment by LoneDev6** [comment]
Can I see a video/screenshot and can you attach config of your ore?
Thanks

Il giorno dom 1 set 2019 alle ore 13:59 Padlick01 <notifications@github.com>
ha scritto:

**Comment by Padlick01** [comment]
video: https://www.youtube.com/watch?v=XyRUP-h8q8w
screenshot of knowledge config: http://siverion.de/pictures/knowledge.png

**Comment by Padlick01** [comment]
btw.. I use Skript for easy things, skript-mirror for little java code.
Screen of my BlockBreakEvent code: http://siverion.de/pictures/BlockBreakEventCode.png

**Comment by TheMGRF** [comment]
Literally just made an issue for something similar to this with McMMO.
(https://github.com/LoneDev6/ItemsAdder/issues/35)

Looks like ItemsAdder's break event is set to MONITOR event priority; so this could be something to do with it. Like I said this also occurs with McMMO. But due to the way Skript works its likely the event priority. Depending on how skript-mirror works you could try adding your own event priority but I dont think it will change much as it appears like an ItemsAdder issue.

**Comment by Padlick01** [comment]
I dont think thats an issue of Skript; 'cause even WorldGuard or other Protection plugins cant stop Itemsadder to drop something; (Also set plugin priority doenst work) 

Also I tested every event priority from lowest to highest to Monitor. Nothing changed at all.

**Comment by LoneDev6** [comment]
Should be fixed in latest version of the plugin, let me know

**Comment by Padlick01** [comment]
Nope, it's not fixed.
Video: https://www.youtube.com/watch?v=bCzgtNVFrMw

**Comment by LoneDev6** [comment]
![immagine](https://user-images.githubusercontent.com/27242001/64350008-3a644680-cff8-11e9-8015-b33698cc6e2c.png)

Try setting your event priority ti HIGH

**Comment by Padlick01** [comment]
At the time where I made that video, it was on highest, so.. :c

**Comment by LoneDev6** [comment]
set it to LOW

**Comment by Padlick01** [comment]
Seems to be working (that ItemsAdder doesn't drop) how it should.
Have tried it 40 times with the same block; could be coincidence or that it is fixed.
But, when you have it in your plugin on normal; why does it work when I set my protection on low.. Pretty weird xD

**Comment by LoneDev6** [comment]
because events are called in this order:
LOWEST
LOW
NORMAL
HIGH
HIGHEST
MONITOR

so LOW is executed before NORMAL, my plugin checks if other functions cancelled the event.
If you set HIGH my plugin executes the function before yours..

**Comment by Padlick01** [comment]
Ok... Havn't worked with this any time. Don't complain about me; 
But that sounds weird... xD Because it's called "priority" - so everyone would think that a priority that is higher would be executed before lower.. But, ok. I am new to this.. xD

**Comment by LoneDev6** [comment]
i had the same issues before, but now I know that call order is like this, strange but it's like this :D

**Comment by Padlick01** [comment]
I know it too now, thank you^^:) 
But it sounds weird anyway. xD
