### ISSUE TITLE
use datapack error [BUG] 

### ISSUE THREAD

**Issue by SnowBees** [LoneDev6/ItemsAdder#367]
https://www.planetminecraft.com/data-pack/incendium-nether-expansion/

I get an error when I add this custom biome using a datapack.
Many data packs have not been validated but it seems that only this pack gives an error.

https://pastebin.com/HxG4WcfC

Since the same error code was repeated, the same error was deleted and only different errors were left.

ItemsAdder-lastversion
paper-161

spigot-1.16.2-lastbuild
spigot does not give an error at startup, but when I go into the nether and create a new chunk I get the same error.

**Comment by LoneDev6** [comment]
Hello!
Thanks for the report, I think it's a Spigot bug, seems that getBiome  returns NULL and that's why you got that error, because it's a custom biome and Spigot doesn't recognize it.
This bug will affect also every other Spigot plugin that checks biomes.
```Java
chunk.getBlock(0, 0, 0).getBiome()
```

The problematic function is this one in **org.bukkit.craftbukkit.v1_16_R2.block.CraftBlock**
```Java
    public static Biome biomeBaseToBiome(IRegistry<BiomeBase> registry, BiomeBase base) {
        return base == null ? null : (Biome)Registry.BIOME.get(CraftNamespacedKey.fromMinecraft(registry.getKey(base)));
    }
```

This should be related to the issue and it's market as fixed, so you can try updating Spigot downloading it from here:
https://serverjars.com/api/fetchJar/spigot/1.16.2

These are the issues: 
https://hub.spigotmc.org/jira/browse/SPIGOT-6064
https://hub.spigotmc.org/jira/browse/SPIGOT-6073

**Comment by SnowBees** [comment]
![4263a40379b1af42791ab6ef46c03a76](https://user-images.githubusercontent.com/48202134/91657551-ca01df80-eafc-11ea-8f82-ff40018d55f8.png)

Apparently, they cannot coexist.
Perhaps spigot&paper also takes a long time to support or may not support it.
It means that there is nothing you can do right now.

**Comment by LoneDev6** [comment]
This is bullshit xD well, it's not a bug of my plugin, it's spigot that cannot find a suitable biome ENUM value cause it's custom.
They have to implement something to address this and fallback to a new ENUM value, maybe CUSTOM would fit.

Only way I can temporary fix this is to add a try and catch and ignore the exception

**Comment by LoneDev6** [comment]
Fixed in the new update, but I hope spigot will add official compatibility with custom biomes, right now it just throws an error

**Comment by SnowBees** [comment]
I have confirmed that spigot gives no error. thank you for your hard work. However, it seems that an error still occurs with paper180. spigot does not give an error, but the datapack elements are not generated, so I'm a little wondering if I should fix this error now.
The minecraft formula also seems to be a trial implementation for custom biomes, so spigot/paper may not add compatibility until it is officially implemented.

**Comment by LoneDev6** [comment]
Try to:
- create a new world in single player
- add the datapack zip file in the datapack folder of the save folder
- exit the singleplayer world
- enter it
- travel in the nether
- use /locatebiome to find the custom biomes
- load some of them travelling (click on the chat message coordinates)
- exit single player
- copy the save folder into your server
- rename the folder, example: custom_nether
- use [multiverse ](https://dev.bukkit.org/projects/multiverse-core)to travel in the custom world **/mv tp custom_nether**

everything should work
