### ISSUE TITLE
[BUG] Disabling ItemsAdder alone

### ISSUE THREAD

**Issue by slipstricker** [LoneDev6/ItemsAdder#404]
**Describe the bug**
[02:02:49] [Server thread/WARN]: java.lang.IllegalThreadStateException: InitializationException
[02:02:49] [Server thread/WARN]: 	at dev.lone.itemsadder.f.f.c.a.v.class.a(a:904)
[02:02:49] [Server thread/WARN]: 	at dev.lone.itemsadder.f.f.c.a.b.b.class.a(a:602)
[02:02:49] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:02:49] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:02:49] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:02:49] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:02:49] [Server thread/WARN]: 	at dev.lone.itemsadder.b.x.class.a(a:539)
[02:02:49] [Server thread/WARN]: 	at dev.lone.itemsadder.f.e.b.d.class.a(a:183)
[02:02:49] [Server thread/WARN]: 	at dev.lone.itemsadder.l.m.class.a(a:371)
[02:02:49] [Server thread/WARN]: 	at dev.lone.itemsadder.f.d.a.a.a.b.class.a(a:98)
[02:02:49] [Server thread/WARN]: 	at dev.lone.itemsadder.api.FontImages.PlayerQuantityHudWapper.class.a(a:830)
[02:02:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296)
[02:02:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
[02:02:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
[02:02:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[02:02:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[02:02:49] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[02:02:49] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v2.1.0
[02:02:49] [Server thread/INFO]: [ItemsAdder] All worlds: saved 0 regions
[02:02:49] [Server thread/INFO]: [ItemsAdder] All worlds: saved 0 regions
[02:02:49] [Craft Scheduler Thread - 22/INFO]: java.net.SocketException: Socket closed

**To Reproduce**
After starting the server, the plugin stops working after a few minutes

**Info (please complete the following information):**
Server version: Paper 1.16.3
Client version: 1.16.3
Plugin version: 2.1.0

**Comment by Xuwznln** [comment]
Can confirm this on my server.

**Comment by LoneDev6** [comment]
Can I get your full server log?

**Comment by Xuwznln** [comment]
The start log is normal.
`[21:33:04] [Craft Scheduler Thread - 257/INFO]: [ItemsAdder] Loaded 36 categories from (ia_gui.yml)
[21:33:04] [Craft Scheduler Thread - 257/INFO]: [ItemsAdder] Loaded items and stuff in 2771ms
[21:33:04] [Craft Scheduler Thread - 414/INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip`

Everything is normal, but world saved twice.
`[21:48:03] [Server thread/INFO]: [ItemsAdder] Saved 0 player stats files
[21:48:03] [Craft Scheduler Thread - 113/INFO]: [ItemsAdder] world_nether: saved 0 regions
[21:48:03] [Craft Scheduler Thread - 598/INFO]: [ItemsAdder] world_nether: saved 0 regions
[21:48:03] [Craft Scheduler Thread - 613/INFO]: [ItemsAdder] rezy: saved 0 regions
[21:48:03] [Craft Scheduler Thread - 611/INFO]: [ItemsAdder] world: saved 0 regions
[21:48:03] [Craft Scheduler Thread - 610/INFO]: [ItemsAdder] spawn: saved 0 regions
[21:48:03] [Craft Scheduler Thread - 615/INFO]: [ItemsAdder] rezy: saved 0 regions
[21:48:03] [Craft Scheduler Thread - 125/INFO]: [ItemsAdder] spawn: saved 0 regions
[21:48:03] [Craft Scheduler Thread - 612/INFO]: [ItemsAdder] world: saved 0 regions
[21:48:09] [Paper Async Chunk Urgent Task Thread/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:bee_nest
[21:49:04] [Craft Scheduler Thread - 600/INFO]: TPS: 20.0 19.99 19.99 19.96 19.98
[21:49:24] [Craft Scheduler Thread - 496/INFO]: TPS: 20.0 19.99 19.99 19.99 19.98
[21:50:03] [Server thread/WARN]: java.lang.IllegalThreadStateException: InitializationException
[21:50:03] [Server thread/WARN]: 	at dev.lone.itemsadder.f.d.a.b.class.a(a:800)
[21:50:03] [Server thread/WARN]: 	at dev.lone.itemsadder.f.i.a.a.c.class.a(a:404)
[21:50:03] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:50:03] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:50:03] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:50:03] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:50:03] [Server thread/WARN]: 	at dev.lone.itemsadder.f.h.a.i.class.a(a:52)
[21:50:03] [Server thread/WARN]: 	at dev.lone.itemsadder.e.u.class.a(a:342)
[21:50:03] [Server thread/WARN]: 	at dev.lone.itemsadder.f.f.c.a.f.class.a(a:165)
[21:50:03] [Server thread/WARN]: 	at dev.lone.itemsadder.c.e.class.a(a:89)
[21:50:03] [Server thread/WARN]: 	at dev.lone.itemsadder.l.d.class.a(a:822)
[21:50:03] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296)
[21:50:03] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
[21:50:03] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
[21:50:03] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[21:50:03] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[21:50:03] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:50:03] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v2.1.0
[21:50:03] [Server thread/INFO]: [ItemsAdder] All worlds: saved 0 regions
[21:50:03] [Server thread/INFO]: [ItemsAdder] All worlds: saved 0 regions
[21:50:04] [Server thread/INFO]: [ItemsAdder] Saved 0 player stats files
[21:50:04] [Server thread/INFO]: [ItemsAdder] Saving custom entities...
[21:50:04] [Server thread/INFO]: [ItemsAdder] Saved 0 custom entities successfully!`

Also get a bug when placing custom mobs and colored water
`[21:33:40] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to ItemsAdder v2.1.0
java.lang.NoSuchMethodError: me.libraryaddict.disguise.disguisetypes.watchers.LivingWatcher.setPitchLock(Ljava/lang/Float;)V
	at dev.lone.itemsadder.f.f.a.i.a(SourceFile:263) ~[?:?]
	at dev.lone.itemsadder.f.f.a.i.a(SourceFile:365) ~[?:?]
	at dev.lone.itemsadder.f.f.a.c.a.b.a(SourceFile:52) ~[?:?]
	at dev.lone.itemsadder.f.f.a.b.h.a(SourceFile:71) ~[?:?]
	at dev.lone.itemsadder.f.f.a.c.a.a.a.a(SourceFile:128) ~[?:?]
	at dev.lone.itemsadder.f.f.a.c.a.d.a(SourceFile:92) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[TTCW.jar:git-Paper-206]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[TTCW.jar:git-Paper-206]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[TTCW.jar:git-Paper-206]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[TTCW.jar:git-Paper-206]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:673) ~[TTCW.jar:git-Paper-206]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:594) ~[TTCW.jar:git-Paper-206]
	at net.minecraft.server.v1_16_R2.WorldServer.addEntity0(WorldServer.java:1182) ~[TTCW.jar:git-Paper-206]
	at net.minecraft.server.v1_16_R2.WorldServer.addEntity(WorldServer.java:1083) ~[TTCW.jar:git-Paper-206]
	at net.minecraft.server.v1_16_R2.WorldAccess.lambda$addAllEntities$0(WorldAccess.java:13) ~[TTCW.jar:git-Paper-206]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.server.v1_16_R2.WorldAccess.addAllEntities(WorldAccess.java:13) ~[TTCW.jar:git-Paper-206]
	at net.minecraft.server.v1_16_R2.SpawnerCreature.spawnMobsInternal(SpawnerCreature.java:254) ~[TTCW.jar:git-Paper-206]
	at net.minecraft.server.v1_16_R2.SpawnerCreature.spawnMobs(SpawnerCreature.java:180) ~[TTCW.jar:git-Paper-206]
	at net.minecraft.server.v1_16_R2.SpawnerCreature.a(SpawnerCreature.java:154) ~[TTCW.jar:git-Paper-206]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:843) ~[TTCW.jar:git-Paper-206]
	at net.minecraft.server.v1_16_R2.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:628) ~[TTCW.jar:git-Paper-206]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:825) ~[TTCW.jar:git-Paper-206]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:743) ~[TTCW.jar:git-Paper-206]
	at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:456) ~[TTCW.jar:git-Paper-206]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358) ~[TTCW.jar:git-Paper-206]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[TTCW.jar:git-Paper-206]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[TTCW.jar:git-Paper-206]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[TTCW.jar:git-Paper-206]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[TTCW.jar:git-Paper-206]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]`

**Comment by LoneDev6** [comment]
Please send the log using a service like pastebin.com

Please create another bug report about the water problem.


Thanks guys

**Comment by LoneDev6** [comment]
Anyway I published an update that should fix the unload problem

**Comment by nrayking** [comment]
Just a heads-up, I downloaded this update and the issue is still occurring. (Thanks for everything you do, by the way! Your plugin is the backbone of our server!)

**Comment by ItsMacs** [comment]
Can confirm I have this problem, too.
I'll leave the full log down here.

https://pastebin.com/zKgBWuC9

**Comment by LoneDev6** [comment]
please update to 2.1.2, issue should be fixed :D
